### ISSUE TITLE
Placing Mugshot through file explorer crashes CAD.

### ISSUE THREAD

**Issue by ArnieBIB** [Jarrrk/HighLife-Website#26]
Hi Kissane, yea when trying to input an image for a mugshot via file explorer it crashes the CAD. Once the CAD crashes it cannot be reopened unless you relog. 

https://user-images.githubusercontent.com/67331944/141653729-2859e889-f089-42d3-b298-86c3b8c34163.mp4

https://streamable.com/s0dyxr

**Comment by NoahO451** [comment]
Update to this issue: Attempting to add a mugshot through the in city CAD will consistently crash the CAD causing you to have to restart your game to have access to the CAD again. To replicate this:
1. Open the CAD and navigate to add a mugshot on a citizen's profile.  
2. Press to upload a mugshot to the profile. 
3. Once the file explorer is open select a picture. 
4. Press open on the file explorer. 
5. The mugshot will fail to load and the CAD will crash with a blank error occurred page with "close" being the only option. 
6. Once you press close on the blank error occurred page you can no longer open the CAD. 

To add to this, a similar effect happens in the browser version of the CAD. Instead of crashing the browser it will try to load the image and fail. It leaves the Upload Mugshot picture and graphic up after trying to load. Follow the above steps 1 through the first part of 5 to replicate this.

**Comment by kissanealex** [comment]
Unfortunately i am unbale to fix this, as there's no way of catching the event, as it seems to be an issue with fivem/windows. I have added a location to paste a image url for now until a better solution is found.
